In [1]:
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline
import random

In [4]:
def generate_data(w=[3], use_less_data_w=0.001, b=5, data_shape=(1000,1), use_less_data_shape=(1000, 5)):
    assert len(w)==data_shape[1], "the w lenghth should equal to the data's second dimension"
    x = np.random.random(data_shape)
    x_2 = np.random.random(use_less_data_shape)
    y = np.dot(x, w) + b + np.random.random(data_shape[0]) + use_less_data_w * np.sum(x_2, axis=1)
    x = np.c_[x, x_2]
    # x = np.stack((x, np.ones(1000)),axis=1)
    return x,y

In [5]:
def generate_data_2(w=[3], middle_w_base=10, b=5, data_shape=(1000,1)):
    assert len(w)==data_shape[1], "the w lenghth should equal to the data's second dimension"
    x = np.random.random(data_shape)
    middle_w = np.random.randint(middle_w_base, size=(data_shape[1]))+1
    y = np.dot(x, w) + b + np.random.random(data_shape[0]) * np.mean(middle_w)
    x = np.multiply(x, middle_w)
#     x = x + middle_w
    return x,y

In [7]:
w= np.random.randint(10, size=50)
w

array([5, 7, 6, 2, 4, 5, 9, 9, 4, 9, 0, 0, 7, 9, 0, 6, 0, 6, 5, 2, 2, 4,
       8, 8, 6, 4, 1, 6, 7, 8, 6, 6, 9, 2, 3, 3, 3, 1, 3, 9, 2, 0, 8, 1,
       5, 3, 6, 0, 0, 0])

In [8]:
np.where(w==0)[0]

array([10, 11, 14, 16, 41, 47, 48, 49], dtype=int64)

In [9]:
x, y = generate_data(w, data_shape=(1000,50), use_less_data_shape=(1000,5))
x_test, y_test = generate_data(w, data_shape=(1000,50), use_less_data_shape=(1000,5))

In [11]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error as MSE
model = LinearRegression()
model.fit(x, y)
MSE(model.predict(x_test),y_test)
# model.score(x_test,y_test)

0.0902230685465411

In [14]:
model.coef_[np.where(w==0)[0]]

array([-0.02735803,  0.00974641,  0.02473195, -0.02281538, -0.01275098,
       -0.02656022,  0.07370953, -0.02000806])

In [18]:
from sklearn.linear_model import Lasso
model = Lasso(alpha=0.01)
model.fit(x, y)
MSE(model.predict(x_test),y_test)
# model.score(x_test,y_test)

0.14548582233365748

In [19]:
model.coef_

array([ 4.86910058,  6.84652345,  5.95744935,  1.8529129 ,  3.90142643,
        4.93918822,  8.88390875,  8.89910865,  3.82311938,  8.86257632,
       -0.        ,  0.        ,  6.88743475,  8.8392203 , -0.        ,
        5.8322493 , -0.        ,  5.89628632,  4.82154727,  1.8312726 ,
        1.87739164,  3.92971526,  7.87981447,  7.96847455,  5.87574356,
        3.93002308,  0.84789317,  5.85497386,  6.83451497,  7.92379129,
        5.88405745,  5.83595709,  8.90340781,  1.88813307,  2.82320091,
        2.87132123,  2.81426517,  0.93620029,  2.78296263,  8.81944012,
        1.83014401, -0.        ,  7.84821256,  0.91719056,  4.93333545,
        2.92108559,  5.81778978, -0.        ,  0.        , -0.        ,
        0.        , -0.        ,  0.        ,  0.        , -0.        ])

In [146]:
MSE(model.predict(x_test),y_test)

0.1513604812681817

In [20]:
column_to_use = model.coef_!=0
column_to_use

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False,  True,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True, False, False, False, False, False, False, False,
       False])

In [21]:
np.where(column_to_use==0)[0]

array([10, 11, 14, 16, 41, 47, 48, 49, 50, 51, 52, 53, 54], dtype=int64)

In [22]:
x_new = x[:, column_to_use]

In [28]:
from sklearn.linear_model import Ridge
model = Ridge(alpha=0.1)
# model = LinearRegression()
model.fit(x_new, y)
# model.score(x_test[:, column_to_use],y_test)
MSE(model.predict(x_test[:, column_to_use]),y_test)

0.08769262320507408

In [29]:
w[column_to_use[:50]]

array([5, 7, 6, 2, 4, 5, 9, 9, 4, 9, 7, 9, 6, 6, 5, 2, 2, 4, 8, 8, 6, 4,
       1, 6, 7, 8, 6, 6, 9, 2, 3, 3, 3, 1, 3, 9, 2, 8, 1, 5, 3, 6])

In [30]:
model.coef_

array([4.99421153, 6.98303413, 6.04340183, 1.99734616, 4.01173255,
       5.0202582 , 8.98479983, 9.0118661 , 4.02141347, 9.01468828,
       7.00424434, 8.95836041, 5.95641611, 6.00433438, 4.9639854 ,
       1.96471758, 2.02356975, 4.0516431 , 7.95805266, 8.06604347,
       5.99517495, 4.02262139, 1.0042141 , 5.9701776 , 6.94968967,
       7.99903528, 6.03212242, 5.99743358, 9.00286092, 1.99488365,
       2.9949938 , 2.97479668, 2.96803719, 1.02687844, 2.9274404 ,
       8.97487637, 1.95835593, 7.92564572, 1.01450759, 5.03679233,
       2.99132004, 5.97259984])

In [31]:
class linear_model:
    def __init__(self, learning_rate=0.01):
        self.coef_ = []
        self.bias = 1
        self.lr = learning_rate
        
    def shuffle_data(self, x, y):
        c = list(zip(x, y))
        random.shuffle(c)
        a, b = zip(*c)
        a = np.array(a)
        b = np.array(b)
        return a, b
        
    def fit(self, X, y, epochs=100, batch_size=8, seed=42):
#         self.coef_ = np.random.random(X.shape[1])
        np.seed = seed
        random.seed(seed)
        self.coef_ = np.ones(X.shape[1])
        assert len(X.shape)==2, "the shape of X need to be 2d"
        assert len(y.shape)==1, "the shape of y need to be 1d"
        assert len(X)==len(y), "len of X need to equal len of y"
        for i in range(epochs):
            for j in range(len(X)//batch_size - 1):
                start = batch_size*j
                end = batch_size*(j+1)
                self.learn_with_batch_size(X[start:end], y[start:end])
            i = len(X)//batch_size - 1
            start = i * batch_size
            self.learn_with_batch_size(X[start:], y[start:])
            X, y = self.shuffle_data(X, y)
                
    def learn_with_batch_size(self, x, label):
        error = np.mean(np.square(np.dot(self.coef_, x.T) + self.bias - label))
        residual = np.dot(self.coef_, x.T) + self.bias - label
        gradient =  np.mean(np.multiply(self.coef_, x).T * residual, axis=1)
        self.coef_ = self.coef_ - gradient * self.lr
        self.bias = self.bias - self.lr * np.mean(residual)
        
    def predict(self, x):
        return np.dot(self.coef_, x.T) + self.bias

    def score(self, x, y):
        return np.mean(np.square(self.predict(x) - y))

In [32]:
x, y = generate_data_2(w, data_shape=(2000,50))

In [35]:
np.max(x, axis=0)

array([9.99830583, 9.98922664, 3.99719407, 5.99806866, 2.9974529 ,
       8.99833708, 0.99990138, 3.99961764, 5.99690862, 6.99708788,
       8.99396538, 6.99891032, 6.99830037, 2.99968955, 7.99924217,
       5.99819094, 9.98911035, 8.99592131, 5.99992025, 6.99434515,
       8.99598179, 6.98977723, 6.99986099, 7.99913486, 2.99890488,
       2.99934694, 4.99977483, 0.99977293, 2.99979523, 4.99996857,
       9.99313873, 2.99779737, 1.99655687, 2.99913645, 8.98997588,
       9.998568  , 5.9986904 , 8.99884   , 7.99337524, 1.99872452,
       5.99878554, 9.9998971 , 7.99797129, 5.99306994, 8.99730412,
       8.98215259, 9.9967338 , 8.9968653 , 4.99974788, 6.99909939])

In [36]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [39]:
model = linear_model(learning_rate=0.001)
# model = LinearRegression()
model.fit(x_train, y_train)
model.score(x_test,y_test)

3.7941179372822567

In [40]:
x_new = (x - np.min(x, axis=0)) / (np.max(x, axis=0) - np.min(x, axis=0))
y_new = (y - np.min(y)) / (np.max(y) - np.min(y))

In [42]:
x_new = (x - np.min(x, axis=0)) / (np.max(x, axis=0) - np.min(x, axis=0))
y_new = (y - np.min(y)) / (np.max(y) - np.min(y))

In [43]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
# sc = MinMaxScaler()
sc = StandardScaler()
sc.fit(x)
x_new = sc.transform(x)
# sc_y = MinMaxScaler()
sc_y = StandardScaler()
y_new = sc_y.fit_transform(y.reshape(-1,1)).reshape(-1)

In [44]:
x_train, x_test, y_train, y_test = train_test_split(x_new, y_new, test_size=0.3, random_state=42)

In [51]:
model = linear_model(learning_rate=0.01)
model.fit(x_train, y_train)
model.score(x_test,y_test)

0.029025830381033492

In [52]:
MSE(model.predict(x_test),y_test)

0.029025830381033492

In [53]:
MSE(sc_y.inverse_transform(model.predict(x_test)), sc_y.inverse_transform(y_test))

3.4866375195891486